5/Models/Ok.cs
namespace Core_1.Models;

class OkText
{
    public int Id { get; set; }
    public string Title { get; set; } = "Title nai";
    public string? Text { get; set; }

}

5/Models/Person.cs
using Microsoft.AspNetCore.Mvc.Rendering; // for SelectListItem
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations; // for List
namespace Core_1.Models;


public class Person
{
    public int Id { get; set; }

    public string? Name { get; set; }
    public int Age { get; set; }
    [Required]
    [Display(Name = "Favorite Language")]
    public string? FavLang { get; set; }
    public string? Gender { get; set; }
    [Phone]
    public string? Phone { get; set; }

    [Required]
    [MinLength(4)]
    public string? Pass { get; set; }
    [Required]
    [Compare("Pass")]
    public string? ConfirmPass { get; set; }
}

5/Controllers/FormController.cs
using Core_1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Core_1.Controllers
{
    public class FormController : Controller
    {
        // GET: /Form or /Form/Index
        [HttpGet]

        public IActionResult Index()
        {
            var person = new Person()
            {
                FavLang = null
            };
            return View("~/Views/Form/Index.cshtml", person);
        }

        // POST: /Form/Index
        [HttpPost]
        public IActionResult Index(Person person)
        {
            if (ModelState.IsValid)
            {
                return Content($"Name: {person.Name}, Age: {person.Age}, Fav: {person.FavLang}, Gender: {person.Gender}");
            }

            // Return the view with the model if validation fails
            return View("~/Views/Form/Index.cshtml", person);
        }

        // GET: /Form/Test
        [HttpGet]
        [Route("Test")]
        public IActionResult Test()
        {
            return Content("Test Form");
        }
    }
}

5/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Core_1.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

5/Controllers/OkController.cs
using Microsoft.AspNetCore.Mvc;
using Core_1.Models;

namespace Core_1.Controllers;

public class OkController : Controller
{
    public IActionResult Index()
    {
        ViewData["Message"] = "Hello";
        return View("~/Views/Ok/Ok.cshtml");
    }

    [Route("text")]
    [Route("Ok/Text")]
    [Route("Ok/OkText")]
    public IActionResult OkText()
    {
        var ok = new OkText()
        {
            Id = 1,
            Title = "ok text 1",
            Text = "Nai kisu e nai"
        };


        return View("~/Views/Ok/Text.cshtml", ok);
    }
    [Route("Chat")]
    [Route("OkChat")]
    [Route("Ok/Chat")]
    [Route("Ok/OkChat")]

    public IActionResult OkChat()
    {
        var ok = new List<OkText>()
        {
            new OkText {Id = 1, Title = "ok text 1",
                    Text = "Nai kisu e nai"},
            new OkText {Id = 2, Title = "ok text 2",
                    Text = "Nai kisu e nai"},
            new OkText {Id = 3, Title = "ok text 3",
                    Text = "Nai kisu e nai"}
        };


        return View("~/Views/Ok/Chat.cshtml", ok);
    }

    [Route("work/{id?}")]
    public string? work(int? id)
    {
        return id != null ? Convert.ToString(id) : "null";
    }
}

5/Views/Home/Index.cshtml
<h1>LOL FrameWork</h1>

<div>
    <a href=@Url.Action("Index", "Ok")>
        OK Index</a>
    <br/>
    <a asp-controller="Ok" asp-action="Index" asp-route-id="2">
        Ok.Index Attr</a>
    <br/>
    <a asp-controller="Ok" asp-action="Index" asp-route-id="44">
        Ok.Work Attr</a>
    <br/>
    <a asp-controller="Ok" asp-action="OkText" asp-route-id="44">
        Ok.Text Attr</a>
    <br/>
     <a asp-controller="Ok" asp-action="OkChat" asp-route-id="44">
        Ok.Chat Attr</a>
    <br/>
    <a asp-controller="Form" asp-action="Index">
        Form.Index Attr</a>
    <br/>
    
</div>
<p>asp-controller needs @("@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers") in _viewimports</p> 

5/Views/Ok/Index.cshtml
<h1>
    OK Index
</h1>

<a href=@Url.Action("Index", "Home")>Home</a>
<br/>
<a asp-controller="Home" asp-action="Index" asp-route-id="10">Home Attr</a>
<br/>

5/Views/Ok/Ok.cshtml
@{
    ViewBag.title = "view bag title";
    @* Layout = "~/Views/Shared/_Layout.cshtml"; *@
}
<h1> OK Ok.cshtml</h1>
@ViewData["Message"]
<div>
    <a href=@Url.Action("Index", "Home")>
        Home</a>
    <br/>
    <a asp-controller="Home" asp-action="Index" asp-route-id='1' asp-route-test="will-it-work"> 
        Home.Attr.Query.NonExistent</a>
</div>    
<p>asp-controller needs @("@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers") in _viewimports</p> 
<br/>

5/Views/Ok/Text.cshtml
@* file Ok but Model OkText *@
@* @model Core_1.Models.OkText *@
@model OkText
<h1>@Model.Title</h1> 
 <p><span>ID: </span> @Model.Id</p>
 <p>@Model.Text</p>   

<a href=@Url.Action("Index", "Home")>Home.Action</a>

5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>@ViewBag.title</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>your in _Layout</h1>
        @RenderBody()
        <script src="" async defer></script>
    </body>
</html>